<?php
/**
 * Gene - Product View Wishlist
 * @var Magento\Wishlist\Block\Catalog\Product\View\AddTo\Wishlist $block
 */
?>
<?php if ($block->isWishListAllowed()) : ?>
    <a href="#"
       class="towishlist"
       data-post='<?= /* @noEscape */ $block->getWishlistParams() ?>'
       data-action="add-to-wishlist">
        <span class="wishlist__label">
             <svg width="21" height="24" viewBox="0 0 14 16" class="icon wishlist__icon">
                    <use xlink:href="#icon-wishlist"></use>
                </svg>
            <?= $block->escapeHtml(__('Wish List')) ?>
        </span>
    </a>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "body": {
            "addToWishlist": <?= /* @noEscape */ $block->getWishlistOptionsJson() ?>
        }
    }
</script>
