<?php
/**
 * Gene - Reviews
 * Overridden to change reviewsTabSelector to a class instead of id
 * @var \Magento\Review\Block\Product\Review $block
 */
?>
<div id="product-review-container" data-role="product-review"></div>
<?= $block->getChildHtml(); ?>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Review/js/process-reviews": {
                "productReviewUrl": "<?= $block->escapeJs($block->escapeUrl($block->getProductReviewUrl())) ?>",
                "reviewsTabSelector": ".js-tab-reviews"
            }
        }
    }
</script>
