<?php
/**
 * Add collapsilbe and SVG
 */

/** @var $block \Magento\Framework\View\Element\Html\Links */
?>
<div class="block account-nav">
    <button type="button" class="title" data-mage-init='{"toggleAdvanced": {"toggleContainers": "#account-nav", "selectorsToggleClass": "active"}}'>
        <strong><?= $block->escapeHtml(__('My Account')) ?></strong>
        <svg width="14" height="16" viewBox="0 0 14 16" class="icon icon-arrow icon-arrow--down">
            <use xlink:href="#icon-arrow"></use>
        </svg>
    </button>
    <div class="content" id="account-nav" style="display: none;">
        <nav class="account-nav">
            <?= $block->getChildHtml() ?>
        </nav>
    </div>
</div>
