<?php
/**
 * Gene - Reviews Summary
 * @var\Magento\Review\Block\Product\ReviewRenderer $block
 */
$url = $block->getReviewsUrl() . '#reviews';
$urlForm = $block->getReviewsUrl() . '#review-form';
?>
<?php if ($block->isReviewEnabled() && $block->getReviewsCount()) : ?>
    <?php $rating = $block->getRatingSummary(); ?>
    <div class="product-reviews-summary<?= !$rating ? ' no-rating' : '' ?>" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
        <?php if ($rating) : ?>
            <div class="rating-summary">
                <span class="label"><span><?= $block->escapeHtml(__('Rating')) ?>:</span></span>
                <div class="rating-result" title="<?= $block->escapeHtmlAttr($rating); ?>%">
                     <span style="width:<?= $block->escapeHtmlAttr($rating); ?>%">
                         <span>
                             <span itemprop="ratingValue"><?= $block->escapeHtml($rating); ?></span>% of <span itemprop="bestRating">100</span>
                         </span>
                     </span>
                </div>
            </div>
        <?php endif;?>
    </div>
<?php endif; ?>
