<?php
/**
 * Gene - Product view attribute
 * @var \Magento\Catalog\Block\Product\View\Description $block
 * Overridden to add itemprop description
 */
// @codingStandardsIgnoreLine
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();
$_call = $block->getAtCall();
$_code = $block->getAtCode();
$_className = $block->getCssClass();
$_attributeLabel = $block->getAtLabel();
$_attributeType = $block->getAtType();
$_attributeAddAttribute = $block->getAddAttribute();

$renderLabel = true;
// if defined as 'none' in layout, do not render
if ($_attributeLabel == 'none') {
    $renderLabel = false;
}

if ($_attributeLabel && $_attributeLabel == 'default') {
    $_attributeLabel = $_product->getResource()->getAttribute($_code)->getStoreLabel();
}
if ($_attributeType && $_attributeType == 'text') {
    $_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code)) ? $_product->getAttributeText($_code) : '';
} else {
    $_attributeValue = $_helper->productAttribute($_product, $_product->$_call(), $_code);
}
?>
<?php if ($_attributeValue) : ?>
    <div class="product attribute <?= $block->escapeHtmlAttr($_className) ?>" <?= $_code == 'description' ? 'itemprop="description"' : '';?>>
        <?php if ($renderLabel) : ?>
            <strong class="type"><?= $block->escapeHtml($_attributeLabel) ?></strong>
        <?php endif; ?>
        <div class="value" <?= /* @noEscape */ $_attributeAddAttribute ?>>
            <?= /* @noEscape */ $_attributeValue ?>
        </div>
    </div>
<?php endif; ?>
