<?php
/**
 * Product list template
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var $_product \Magento\Catalog\Model\Product
 */
use Magento\Framework\App\Action\Action;

$_productCollection = $block->getLoadedProductCollection();
// @codingStandardsIgnoreStart
$wishListHelper = $this->helper('Magento\Wishlist\Helper\Data');
$_catalogHelper = $this->helper('Magento\Catalog\Helper\Output');
$_geneCatalogHelper = $this->helper('Gene\Framework\Helper\CatalogListProduct');
$geneRoundelHelper = $this->helper('Gene\Roundel\Helper\Data');
$roundelEnabled = $geneRoundelHelper->isEnabledProductList();
// @codingStandardsIgnoreEnd
$viewMode = $_geneCatalogHelper->getCatalogData()->getViewMode();

$showWishlist = true;

$pos = $block->getPositioned();

if (!$_productCollection->count()) : ?>
    <div class="message info empty">
        <div>
            <?= $block->escapeHtml(__('We can\'t find products matching the selection.')) ?>
        </div>
    </div>
<?php else : ?>

    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <ol class="products items product-items product-items--<?= $block->escapeHtmlAttr($viewMode) ?>">
            <?php foreach ($_productCollection as $_product) :
                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                $_productName = $_catalogHelper->productAttribute($_product, $_product->getName(), 'name');
                $roundel = $geneRoundelHelper->getRoundel($_product); ?>

                <li class="item product product-item">
                    <article class="product-item-info"
                                data-container="product-<?= $block->escapeHtmlAttr($viewMode) ?>"
                                itemscope
                                itemtype="http://schema.org/Product">

                        <?php if (!empty($roundel[0]) && $roundelEnabled) : ?>
                            <div class="gene-roundel <?= $block->escapeHtmlAttr($roundel[1]); ?>">
                                <?= $block->escapeHtml($roundel[0]); ?>
                            </div>
                        <?php endif; ?>

                        <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                            class="product photo product-item-photo ratio"
                            style="padding-bottom: 125%"
                            tabindex="-1"
                            rel="bookmark">
                            <img src="data:image/gif;base64,R0lGODlhAQABAIAAAMLCwgAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="
                                    class="product-image-photo"
                                    loading="lazy"
                                    itemprop="image"
                                    data-src="<?= $block->escapeUrl($_geneCatalogHelper->getProductImageUrl($_product)); ?>"
                                    srcset="<?= $block->escapeUrl($_geneCatalogHelper->getProductImageUrl($_product)); ?> 1x,
                                    <?= $block->escapeUrl($_geneCatalogHelper->getRetinaProductImageUrl($_product)); ?> 2x"
                                    alt="<?= $block->escapeHtmlAttr($_productName); ?>"/>
                            <noscript>
                                <img src="<?= $block->escapeUrl($_geneCatalogHelper->getRetinaProductImageUrl($_product)); ?>"
                                        alt="<?= $block->escapeHtmlAttr($_productName); ?>">
                            </noscript>
                        </a>

                        <div class="product details product-item-details">
                            <h3 class="product name product-item-name"
                                itemprop="name">
                                <a class="product-item-link"
                                    href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                                    rel="bookmark">
                                    <?= $block->escapeHtml($_productName) ?>
                                </a>
                            </h3>

                            <div class="product-item-inner">

                                <?php if ($_geneCatalogHelper->getShortDescription($_product)) : ?>
                                    <div class="product description product-item-description"
                                            itemprop="description">
                                        <?= /* @noEscape */ $_geneCatalogHelper->getShortDescription($_product); ?>
                                    </div>
                                <?php endif; ?>

                                <?= /* @noEscape */  $block->getProductPrice($_product) ?>

                                <div class="product-item-reviews__container">
                                    <?= $block->getReviewsSummaryHtml($_product, $_geneCatalogHelper->getTemplateType()) ?>
                                </div>
                                
                                <?= $block->getProductDetailsHtml($_product) ?>

                                <div class="product actions product-item-actions"<?= /* @noEscape */ strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                    <div class="actions-primary"<?= /* @noEscape */  strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                        <?php if ($_product->isSaleable()) : ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <form data-role="tocart-form"
                                                    data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
                                                    action="<?= /* @noEscape */ $postParams['action'] ?>"
                                                    method="post">
                                                <input type="hidden"
                                                        name="product"
                                                        value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                                <input type="hidden"
                                                        name="<?= /* @noEscape */  Action::PARAM_NAME_URL_ENCODED ?>"
                                                        value="<?= /* @noEscape */  $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                <?= $block->getBlockHtml('formkey') ?>
                                                <button type="submit"
                                                        title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                        class="action tocart primary">
                                                    <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                </button>
                                            </form>
                                        <?php else : ?>
                                            <?php if ($_product->isAvailable()) : ?>
                                                <div class="stock available">
                                                    <span><?= $block->escapeHtml(__('In stock')) ?></span>
                                                </div>
                                            <?php else : ?>
                                                <div class="stock unavailable">
                                                    <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                                </div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                    <?php if ($showWishlist) : ?>
                                        <div class="actions-secondary" data-role="add-to-links">
                                            <?php if ($wishListHelper->isAllow() && $showWishlist) : ?>
                                                <a href="#"
                                                data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_product) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                    <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                                    <svg width="14" height="16" viewBox="0 0 14 16" class="icon icon-wishlist">
                                                        <use xlink:href="#icon-wishlist"></use>
                                                    </svg>
                                                </a>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>                            
                            </div>
                        </div>
                    </article>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>

    <?= $block->getChildBlock('toolbar')
        ->setTemplate('Magento_Catalog::product/list/toolbar-bottom.phtml')
        ->toHtml(); ?>

    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @noEscape */ $_product->getSku() ?>"
                }
            }
        }

        </script>
    <?php endif; ?>
<?php endif; ?>
