<?php
/**
 * Modified to fix template to use Product Grid layout
 */

/** @var \Magento\Wishlist\Block\Share\Wishlist $block */
?>

<?php if ($block->hasWishlistItems()) : ?>
    <form class="form shared wishlist" action="<?= $block->escapeUrl($block->getUrl('wishlist/index/update')) ?>" method="post">
        <ol class="products items product-items product-items--grid">
            <?php foreach ($block->getWishlistItems() as $item) : ?>
                <?php
                $product = $item->getProduct();
                $isVisibleProduct = $product->isVisibleInSiteVisibility();
                ?>
                <li class="item product product-item">
                    <article class="product-item-info"
                        data-container="product-grid"
                        itemscope
                        itemtype="http://schema.org/Product">
                        <a
                            class="product photo product-item-photo"
                            href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>"
                            title="<?= $block->escapeHtmlAttr($product->getName()) ?>"
                            tabindex="-1"
                            rel="bookmark"
                        >
                            <?= $block->getImage($product, 'customer_shared_wishlist')->toHtml() ?>
                        </a>

                        <div class="product details product-item-details">
                            <h3 class="product name product-item-name"
                                itemprop="name">
                                <a class="product-item-link"
                                    href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>"
                                    rel="bookmark">
                                    <?= $block->escapeHtml($product->getName()) ?>
                                </a>
                            </h3>

                            <div class="product-item-inner">
                            
                                <?=
                                    $block->getProductPriceHtml(
                                        $product,
                                        'wishlist_configured_price',
                                        \Magento\Framework\Pricing\Render::ZONE_ITEM_LIST,
                                        ['item' => $item]
                                    );
                                ?>
                                
                                <?= $block->getDetailsHtml($item) ?>

                                <div class="product actions product-item-actions">
                                    <div class="actions-primary">
                                        <?php if ($product->isSaleable()) : ?>
                                            <?php if ($isVisibleProduct) : ?>
                                                <button type="button"
                                                        title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                        data-post='<?= /* @noEscape */ $block->getSharedItemAddToCartUrl($item) ?>'
                                                        class="action tocart">
                                                    <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                </button>
                                            <?php endif ?>
                                        <?php endif; ?>

                                        <a href="#" data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($item) ?>'  onclick="location.assign(this.href); return false;" class="action towishlist" data-action="add-to-wishlist">
                                            <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                        </a>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </article>
                </li>
            <?php endforeach ?>
        </ol>

        <div class="actions-toolbar">
            <?php if ($block->isSaleable()) : ?>
                <div class="primary">
                    <button type="button"
                            title="<?= $block->escapeHtmlAttr(__('Add All to Cart')) ?>"
                            data-post='<?= $block->escapeUrl($block->getSharedAddAllToCartUrl()) ?>'
                            class="action tocart primary">
                        <span><?= $block->escapeHtml(__('Add All to Cart')) ?></span>
                    </button>
                </div>
            <?php endif;?>
            <div class="secondary">
                <a href="<?= $block->escapeUrl($block->getBackUrl()) ?>" class="action back">
                    <span><?= $block->escapeHtml(__('Back')) ?></span>
                </a>
            </div>
        </div>
    </form>
<?php else : ?>
    <div class="message info empty"><div><?= $block->escapeHtml(__('Wish List is empty now.')) ?></div></div>
<?php endif ?>
