<?php
/**
 * Category layered navigation
 * Core template with icons added
 * @var \Magento\LayeredNavigation\Block\Navigation $block
 */
?>
<?php if ($block->canShowBlock()) : ?>
    <div class="filter">

        <h3 class="filter-title">
            <?= $escaper->escapeHtml(__('Filter')) ?>
        </h3>

        <div class="filter-content">
            <?= $block->getChildHtml('state') ?>

            <?php if ($block->getLayer()->getState()->getFilters()) : ?>
                <div class="filter-actions">
                    <a href="<?= $escaper->escapeUrl($block->getClearUrl()) ?>"
                       class="filter-actions__clear">
                        <span><?= $escaper->escapeHtml(__('Reset Filters')) ?></span>
                    </a>
                </div>
            <?php endif; ?>

            <?php foreach ($block->getFilters() as $filter) : ?>
                <?php if ($filter->getItemsCount()) : ?>
                    <details class="filter-category">
                        <summary class="filter-category-name">
                            <span><?= $escaper->escapeHtml(__($filter->getName())) ?></span>
                            <span class="filter-category-name__icons">
                                <svg width="14" height="14" viewBox="0 0 14 16" class="icon icon-plus">
                                    <use xlink:href="#icon-add"></use>
                                </svg>
                                <svg width="14" height="14" viewBox="0 0 22 19" class="icon icon-minus">
                                    <use xlink:href="#icon-remove"></use>
                                </svg>
                            </span>
                        </summary>
                        <div class="filter-category__content">
                            <?= /* @escapeNotVerified */ $block->getChildBlock('renderer')->render($filter) ?>
                        </div>
                    </details>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
