<?php
/**
 * Gene - Bundle Product - Summary
 * Remove Title + Product Name & Image + bundle-summary container
 * @var \Magento\Catalog\Block\Product\View $block
 */
$_product = $block->getProduct();
?>
<?php if ($_product->isSaleable() && $block->hasOptions()) : ?>
    <div id="bundleSummary"
         class="block-bundle-summary"
         data-mage-init='{"sticky":{"container": ".product-add-form"}}'>
        <div class="content">
            <div class="bundle-info">
                <div class="product-details">
                    <?php if ($_product->getIsSalable()) : ?>
                        <p class="available stock" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                            <span><?= $block->escapeHtml(__('In stock')) ?></span>
                        </p>
                    <?php else : ?>
                        <p class="unavailable stock" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                            <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                        </p>
                    <?php endif; ?>
                    <?= $block->getChildHtml('', true) ?>
                </div>
            </div>
        </div>
    </div>
    <script type="text/x-magento-init">
    {
        ".product-add-form": {
            "slide": {
                "slideSpeed": 1500,
                "slideSelector": "#bundle-slide",
                "slideBackSelector": ".action.customization.back",
                "bundleProductSelector": "#bundleProduct",
                "bundleOptionsContainer": ".product-add-form"
                <?php if ($block->isStartCustomization()) : ?>
                ,"autostart": true
                <?php endif;?>
            }
        }
    }
</script>
<?php endif; ?>
