
<?php
/**
 * Gene Framework - Checkout Cart Item Default
 * Changes: Rearranged columns, added iterator(+, -) for quantity
 * @var \Magento\Checkout\Block\Cart\Item\Renderer $block
 */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
// @codingStandardsIgnoreLine
$helper = $this->helper('Magento\Msrp\Helper\Data');
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
?>
<tbody class="cart item cart__item">
    <tr class="item-info">
        <td class="col item col-img item-info__column">
            <?php if ($block->hasProductUrl()) :?>
                <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"
                   title="<?= $block->escapeHtml($block->getProductName()) ?>"
                   tabindex="-1"
                   class="product-item-photo">
            <?php else :?>
                <span class="product-item-photo">
            <?php endif;?>
                <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
            <?php if ($block->hasProductUrl()) :?>
                </a>
            <?php else : ?>
                </span>
            <?php endif; ?>
        </td>
        <td data-th="<?= $block->escapeHtml(__('Item')) ?>"
            class="col item is-hidden-mobile"
            data-product-name="<?= $block->escapeHtml($block->getProductName()); ?>">
            <div class="product-item-details">
                <strong class="product-item-name">
                    <?php if ($block->hasProductUrl()) :?>
                        <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>">
                            <?= $block->escapeHtml($block->getProductName()) ?></a>
                    <?php else : ?>
                        <?= $block->escapeHtml($block->getProductName()) ?>
                    <?php endif; ?>
                </strong>
                <?php if ($_options = $block->getOptionList()) :?>
                    <dl class="item-options">
                        <?php foreach ($_options as $_option) : ?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                            <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                            <dd>
                                <?php if (isset($_formatedOptionValue['full_view'])) : ?>
                                    <?= /* @noEscape */ $_formatedOptionValue['full_view'] ?>
                                <?php else : ?>
                                    <?= /* @noEscape */ $_formatedOptionValue['value'] ?>
                                <?php endif; ?>
                            </dd>
                        <?php endforeach; ?>
                    </dl>
                <?php endif;?>
                <?php if ($messages = $block->getMessages()) : ?>
                    <?php foreach ($messages as $message) : ?>
                        <div class="cart item message <?= $block->escapeHtmlAttr($message['type']) ?>">
                            <div><?= $block->escapeHtml($message['text']) ?></div>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock) : ?>
                    <?= $addInfoBlock->setItem($_item)->toHtml() ?>
                <?php endif;?>
            </div>
        </td>

        <?php if ($canApplyMsrp) : ?>
            <td class="col msrp is-hidden-mobile" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                <span class="pricing msrp">
                    <span class="msrp notice"><?= $block->escapeHtml(__('See price before order confirmation.')) ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map" id="<?= $block->escapeHtmlAttr($helpLinkId) ?>"
                       data-mage-init='{"addToCart": {
                       "helpLinkId": "#<?= $block->escapeHtml($helpLinkId) ?>",
                       "productName": "<?= $block->escapeHtml($product->getName()) ?>",
                       "showAddToCart": false
                       }}'>
                        <span><?= $block->escapeHtml(__("What's this?")) ?></span>
                    </a>
                </span>
            </td>
        <?php else : ?>
            <td class="col price is-hidden-mobile" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                <?= $block->getUnitPriceHtml($_item) ?>
            </td>
        <?php endif; ?>
        <td class="col qty item-info__column" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
            <div class="is-hidden-desktop is-hidden-tablet product-item-details-mobile">
                <strong class="product-item-name">
                    <?php if ($block->hasProductUrl()) :?>
                        <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                    <?php else : ?>
                        <?= $block->escapeHtml($block->getProductName()) ?>
                    <?php endif; ?>
                </strong>
                <div class="price-mobile">
                    <?php if ($canApplyMsrp) : ?>
                        <span class="pricing msrp">
                            <span class="msrp notice"><?= $block->escapeHtml(__('See price before order confirmation.')) ?></span>
                            <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                            <a href="#" class="action help map" id="<?= $block->escapeHtmlAttr($helpLinkId) ?>"
                               data-mage-init='{"addToCart":{
                               "helpLinkId": "#<?=  $block->escapeHtml($helpLinkId)?>",
                               "productName": "<?=  $block->escapeHtml($product->getName()) ?>",
                               "showAddToCart": false
                               }}'>
                                <span><?=  $block->escapeHtml(__("What's this?")) ?></span>
                            </a>
                        </span>
                    <?php else : ?>
                        <?= $block->getUnitPriceHtml($_item) ?>
                    <?php endif; ?>
                </div>
                <?php if ($_options = $block->getOptionList()) :?>
                    <dl class="item-options">
                        <?php foreach ($_options as $_option) : ?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                            <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                            <dd>
                                <?php if (isset($_formatedOptionValue['full_view'])) : ?>
                                    <?= /* @noEscape */ $_formatedOptionValue['full_view'] ?>
                                <?php else : ?>
                                    <?= /* @noEscape */ $_formatedOptionValue['value'] ?>
                                <?php endif; ?>
                            </dd>
                        <?php endforeach; ?>
                    </dl>
                <?php endif;?>
                <?php if ($messages = $block->getMessages()) : ?>
                    <?php foreach ($messages as $message) : ?>
                        <div class="cart item message <?= $block->escapeHtmlAttr($message['type']) ?>">
                            <div><?= $block->escapeHtml($message['text']) ?></div>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock) : ?>
                    <?= $addInfoBlock->setItem($_item)->toHtml() ?>
                <?php endif;?>
            </div>
            <div class="qty__wrapper" data-mage-init='{"GeneQtyControls": {}}'>
                <div class="qty__container">

                    <button type="button"
                            class="qty__button js-qty-iterator"
                            data-iterator-type="decrement"
                            aria-label="<?= $block->escapeHtmlAttr(__('Reduce quantity by one')); ?>">
                        <svg width="20" height="20" viewBox="0 0 16 16" class="icon">
                            <use xlink:href="#icon-remove"></use>
                        </svg>
                    </button>

                    <label class="label qty__label sr-only"
                           for="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty">
                        <span><?= $block->escapeHtml(__('Qty')) ?></span>
                    </label>

                    <input id="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty"
                           name="cart[<?= $block->escapeHtmlAttr($_item->getId()) ?>][qty]"
                           data-cart-item-id="<?= $block->escapeHtml($_item->getSku()) ?>"
                           value="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                           type="number"
                           size="4"
                           title="<?= $block->escapeHtml(__('Qty')) ?>"
                           class="qty__input qty js-qty"
                           data-validate="{required:true,'validate-greater-than-zero':true}"
                           data-role="cart-item-qty"/>

                    <button type="button"
                            class="qty__button js-qty-iterator"
                            data-iterator-type="increment"
                            aria-label="<?= $block->escapeHtmlAttr(__('Increase quantity by one')); ?>">
                        <svg width="20" height="20" viewBox="0 0 1151.25 1151.2499" class="icon">
                            <use xlink:href="#icon-add"></use>
                        </svg>
                    </button>

                </div>
                <button class="qty__update js-update-qty">
                    <span><?= $block->escapeHtmlAttr(__('Update')); ?></span>
                </button>
            </div>
        </td>

        <td class="col subtotal is-hidden-mobile" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
            <?php if ($canApplyMsrp) : ?>
                <span class="cart msrp subtotal">--</span>
            <?php else : ?>
                <?= $block->getRowTotalHtml($_item) ?>
            <?php endif; ?>
        </td>

        <td class="col item-actions" colspan="100">
            <div class="actions-toolbar">
                <?= /* @noEscape */ $block->getActions($_item) ?>
            </div>
        </td>
    </tr>
</tbody>
