<?php
/**
 * Gene - Bundle Product - Options
 * Remove Title, Remove ChildHtml (Back to Button)
 * @var Magento\Bundle\Block\Catalog\Product\View\Type\Bundle $block
 */

$product = $block->getProduct();
// @codingStandardsIgnoreLine
$helper = $this->helper(\Magento\Catalog\Helper\Output::class);
$stripSelection = $product->getConfigureMode() ? true : false;
$options = $block->decorateArray($block->getOptions($stripSelection));
?>
<?php if ($product->isSaleable()) : ?>
    <?php if (count($options)) : ?>
        <script type="text/x-magento-init">
            {
                "#product_addtocart_form": {
                    "priceBundle": {
                        "optionConfig": <?= /* @noEscape */ $block->getJsonConfig() ?>,
                        "controlContainer": ".field.option"
                    }
                }
            }
        </script>
        <fieldset class="fieldset fieldset-bundle-options">
            <?php foreach ($options as $option) : ?>
                <?php
                if (!$option->getSelections()) {
                    continue;
                } else {
                    echo $block->getOptionHtml($option);
                }
                ?>
            <?php endforeach; ?>
        </fieldset>
    <?php else : ?>
        <p class="empty"><?= $block->escapeHtml(__('No options of this product are available.')) ?></p>
    <?php endif; ?>
<?php endif;?>
