<?php
/**
 * Split Logo out from Menu Toggle & add aria label
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */

$storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();
$logoTitle = $block->getLogoAlt() ? $block->getLogoAlt() : __('%1 Logo', $storeName)
?>
<a class="logo"
   href="<?= $block->escapeUrl($block->getUrl('')) ?>"
   title="<?= $block->escapeHtmlAttr($logoTitle) ?>"
   aria-label="store logo">
   <img src="<?= $block->escapeUrl($block->getLogoSrc()) ?>"
        title="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>"
        alt="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>"
        width="180"
        height="50"
    />
</a>
