<?php
/**
 * Gene Framework
 * CodeStandards + Add Ajax Add To Cart + set Wishlist & Compare to false
 * @var \Magento\CatalogWidget\Block\Product\ProductsList $block
 */

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreStart
$wishListHelper = $this->helper(\Magento\Wishlist\Helper\Data::class);
$compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class);
$geneRoundelHelper = $this->helper(\Gene\Roundel\Helper\Data::class);
$roundelEnabled = $geneRoundelHelper->isEnabledProductList();
// @codingStandardsIgnoreEnd
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) : ?>
    <?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = false;
    $showCompare = false;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;
    ?>
    <div class="block block-products-list <?= /* @noEscape */ $mode ?>">
        <?php if ($block->getTitle()) : ?>
            <div class="block-title">
                <strong><?= $block->escapeHtml(__($block->getTitle())) ?></strong>
            </div>
        <?php endif ?>
        <div class="block-content">
            <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
            <ol class="products items product-items product-items--<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $type ?>">
                <?php $iterator = 1; ?>
                <?php foreach ($items as $_item) : ?>
                    <?= /* @noEscape */ ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>

                    <?php $roundel = $geneRoundelHelper->getRoundel($_item); ?>

                    <article class="product-item-info">

                        <?php if (!empty($roundel[0]) && $roundelEnabled) : ?>
                            <div class="gene-roundel <?= $block->escapeHtmlAttr($roundel[1]); ?>">
                                <?= $block->escapeHtml($roundel[0]); ?>
                            </div>
                        <?php endif; ?>

                        <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo">
                            <?= $block->getImage($_item, $image)->toHtml() ?>
                        </a>

                        <div class="product details product-item-details">

                            <h3 class="product name product-item-name">
                                <a class="product-item-link"
                                    title="<?= $block->escapeHtml($_item->getName()) ?>"
                                    href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>">
                                    <?= $block->escapeHtml($_item->getName()) ?>
                                </a>
                            </h3>

                            <div class="product-item-inner">

                                <?= $block->getProductPriceHtml($_item, $type) ?>

                                <?php if ($templateType) : ?>
                                    <div class="product-item-reviews__container">
                                        <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                    </div>
                                <?php endif; ?>

                                <?= $block->getProductDetailsHtml($_item) ?>

                                <?php if ($showWishlist || $showCompare || $showCart) : ?>
                                    <div class="product actions product-item-actions">
                                        <?php if ($showCart) : ?>
                                            <div class="actions-primary">
                                                <?php if ($_item->isSaleable()) : ?>
                                                    <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                    <form data-role="widget-tocart-form"
                                                          data-product-sku="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                                                          action="<?= $block->escapeUrl($postParams['action']) ?>" method="post">
                                                        <input type="hidden" name="product" value="<?= $block->escapeHtmlAttr($postParams['data']['product']) ?>">
                                                        <input type="hidden"
                                                               name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                                               value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                        <?= $block->getBlockHtml('formkey') ?>
                                                        <button type="submit"
                                                                title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                                class="action tocart primary">
                                                            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                        </button>
                                                    </form>
                                                <?php else : ?>
                                                    <?php if ($_item->getIsSalable()) : ?>
                                                        <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                                    <?php else : ?>
                                                        <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                        <?php if ($showWishlist || $showCompare) : ?>
                                            <div class="actions-secondary" data-role="add-to-links">
                                                <?php if ($wishListHelper->isAllow() && $showWishlist) : ?>
                                                    <a href="#"
                                                    data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                        <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                                        <svg width="14" height="16" viewBox="0 0 14 16" class="icon icon-wishlist">
                                                            <use xlink:href="#icon-wishlist"></use>
                                                        </svg>
                                                    </a>
                                                <?php endif; ?>
                                                <?php if ($block->getAddToCompareUrl() && $showCompare) : ?>
                                                    <a href="#" class="action tocompare" data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>' title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                        <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </article>
                    <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
                <?php endforeach ?>
            </ol>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
                {
                    "[data-role=widget-tocart-form]": {
                        "catalogAddToCart": {}
                    }
                }
            </script>
    <?php endif; ?>
<?php endif;?>

