<?php
/**
 * Customer log in
 *
 * The changes are:
 * Replaced 'strong' tags with 'H3'
 * Changed 'pass' to 'password' on classes and Ids
 * @var \Magento\Customer\Block\Form\Login $block
 */
?>
<section class="block block-customer-login">
    <h3 id="block-customer-login-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Registered Customers')) ?></h3>
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>">
                <p class="field note"><?= $block->escapeHtml(__('If you have an account, sign in with your email address.')) ?></p>
                <div class="field email required">
                    <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                    <div class="control">
                        <input name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <div class="field password required">
                    <label for="password" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                    <div class="control">
                        <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> class="input-text" id="password" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}">
                    </div>
                </div>
                <?= $block->getChildHtml('form_additional_info') ?>

                    <button type="submit" class="action login primary button-login" name="send" id="send2">
                        <?= $block->escapeHtml(__('Sign In')) ?>
                    </button>
                    <a class="action remind account-secondary-link" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>">
                        <?= $block->escapeHtml(__('Forgot Your Password?')) ?>
                    </a>
            </fieldset>
        </form>
    </div>
</section>
