<?php

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Cart $block */

/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
/** @var \Magento\Wishlist\ViewModel\AllowedQuantity $viewModel */
$viewModel = $block->getData('allowedQuantityViewModel');
$allowedQty = $viewModel->setItem($item)->getMinMaxQty();
?>
<?php foreach ($block->getChildNames() as $childName) : ?>
    <?= /* @noEscape */ $block->getLayout()->renderElement($childName, false) ?>
<?php endforeach;?>
<div class="box-tocart">
    <fieldset class="fieldset">
    <?php if ($item->canHaveQty() && $product->isVisibleInSiteVisibility()) : ?>
        <div class="field qty">
            <div class="control">
                <div class="qty__wrapper qty__wrapper--center" data-mage-init='{"GeneQtyControls": {}}'>
                    <div class="qty__container">

                        <button type="button"
                                class="qty__button js-qty-iterator"
                                data-iterator-type="decrement"
                                aria-label="<?= $block->escapeHtmlAttr(__('Reduce quantity by one')); ?>">
                            <svg width="20" height="20" viewBox="0 0 16 16" class="icon">
                                <use xlink:href="#icon-remove"></use>
                            </svg>
                        </button>

                        <label class="label qty__label sr-only"
                               for="qty[<?= $block->escapeHtmlAttr($item->getId()) ?>]">
                            <span><?= $block->escapeHtml(__('Qty')) ?></span>
                        </label>

                        <input type="number"
                               data-role="qty"
                               id="qty[<?= $block->escapeHtmlAttr($item->getId()) ?>]"
                               class="input-text qty qty__input"
                               data-validate="{
                               'required-number':true,
                               'validate-greater-than-zero':true,
                               'validate-item-quantity': {
                                    'minAllowed':<?= /* @noEscape */ $allowedQty['minAllowed'] ?>,
                                    'maxAllowed':<?= /* @noEscape */ $allowedQty['maxAllowed'] ?>
                                    }
                                }"
                               name="qty[<?= $block->escapeHtmlAttr($item->getId()) ?>]"
                               value="<?= /* @noEscape */ $block->getAddToCartQty($item) * 1 ?>"
                            <?= $product->isSaleable() ? '' : 'disabled="disabled"' ?>>

                        <button type="button"
                                class="qty__button js-qty-iterator"
                                data-iterator-type="increment"
                                aria-label="<?= $block->escapeHtmlAttr(__('Increase quantity by one')); ?>">
                            <svg width="20" height="20" viewBox="0 0 1151.25 1151.2499" class="icon">
                                <use xlink:href="#icon-add"></use>
                            </svg>
                        </button>

                    </div>
                    <button class="qty__update js-update-qty">
                        <span><?= $block->escapeHtmlAttr(__('Update')); ?></span>
                    </button>
                </div>

            </div>
        </div>
    <?php endif; ?>
    <?php if ($product->isSaleable()) : ?>
    <div class="product-item-actions">
        <div class="actions-primary">
            <button type="button" data-role="tocart" data-post='<?= /* @noEscape */ $block->getItemAddToCartParams($item) ?>' title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>" data-item-id="<?= $block->escapeHtmlAttr($item->getId()) ?>" class="action tocart primary">
                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
            </button>
        </div>
    </div>
    <?php else : ?>
        <?php if ($product->getIsSalable()) : ?>
            <p class="available stock" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                <span><?= $block->escapeHtml(__('In stock')) ?></span>
            </p>
        <?php else : ?>
            <p class="unavailable stock" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
            </p>
        <?php endif; ?>
    <?php endif; ?>
    </fieldset>
</div>
