<?php
/**
 * Added Icon and CSS class js-menu-parent-link-top
 * @var \Snowdog\Menu\Block\NodeType\Category $block
 */
$nodeId = $block->getId();
$class = $block->getMenuClass();
$categoryUrl = $block->getCategoryUrl($nodeId);
$categoryUrl = $categoryUrl ?: '#';
$dataAttribute = '';
$isParent = $block->getIsParent();
$level = $block->getLevel();
// $categoryThumb = $block->getImageThumb();

$imageThumb = $block->getImageThumb($nodeId);

if ($block->getIsViewAllLink()) {
    $title = __('View All');
    $classLink = $class . '__inner-link';
} else {
    $classLink = $class . '__link ' . $class . '__link--level' . $level;
    $title = $block->getTitle();

    if ($nodeId && $isParent) {
        $dataAttribute = ' data-menu="menu-' . $nodeId . '"';
        $dataAttribute .= ' aria-expanded="false" aria-haspopup="true"';
        $classLink .= ' js-menu-parent-link';
    }

    if ($block->isCurrentCategory($nodeId)) {
        $classLink .= ' current';
    }

    if ($level === '0') {
        $classLink .= ' js-menu-parent-link-top';
    }
}
?>
<a  <?php if ($block->getNodeFontColor() || $block->getNodeFontWeight()) : ?>
    style="color: <?= $block->getNodeFontColor() ?>; font-weight: <?= $block->getNodeFontWeight() ?>"
    <?php endif; ?>
    href="<?= $categoryUrl ?>"
    class="<?= $classLink ?>"
    <?= $dataAttribute ?>
>
    <?php if ($level === '0') : ?>
        <div class="category-thumb">
            <?php if ($imageThumb) : ?>
                <img src="<?= $imageThumb; ?>" alt="" />
            <?php endif; ?>
        </div>
    <?php endif; ?>
    <span><?= $title ?></span>
</a>
